version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/volume
    environment:
      - POSTGRES_DB=class
      - POSTGRES_USER=vasya
      - POSTGRES_PASSWORD=qwerty12345